# Numpy Basics Quiz

1.	Objective: How do you import the NumPy library in Python?
2.	Objective: What function in NumPy is used to create an array?
3.	Objective: How do you create a 1D NumPy array containing the numbers 0 to 9?
4.	Objective: How do you create a 2D NumPy array with shape (3, 3) filled with zeros?
5.	Objective: How do you create an identity matrix of size 4x4?
6.	Objective: How do you get the shape of a NumPy array arr?
7.	Objective: What function is used to get the total number of elements in a NumPy array arr?
8.	Objective: How do you get the data type of elements in a NumPy array arr?
9.	Objective: How do you change the data type of elements in a NumPy array arr to float?
10.	Objective: How do you create a 3x3 NumPy array with random values between 0 and 1?
11.	Objective: How do you flatten a 2D NumPy array arr into a 1D array?
12.	Objective: How do you reshape a 1D array arr of size 12 into a 3x4 array?
13.	Open-ended: Write a code snippet to create a 5x5 matrix with values 1, 2, 3, ..., 25.
14.	Open-ended: Write a code snippet to create a 1D array of 20 linearly spaced values between 0 and 5.
15.	Open-ended: Write a code snippet to create a 3x3 matrix where the diagonal elements are 1 and the off-diagonal elements are 0.
16.	Open-ended: Write a code snippet to create a 4x4 matrix filled with the value 7.
17.	Open-ended: Write a code snippet to create an array containing the even numbers from 10 to 30.
18.	Open-ended: Write a code snippet to create an array of 10 random integers between 50 and 100.
19.	Exercise: Write a function that takes two arrays and returns their element-wise product.
20.	Exercise: Write a function that takes an array and returns the maximum and minimum values.
21.	Exercise: Write a function that normalizes an array (scales all values between 0 and 1).
22.	Exercise: Write a function that takes an array and returns the index of the maximum value.
23.	Exercise: Write a function that takes a 2D array and returns the sum of each row.
24.	Exercise: Write a function that takes a 2D array and returns the sum of each column.
25.	Exercise: Write a function that takes a 2D array and returns the transpose of the array.
26.	Exercise: Write a function that takes an array and removes all the even numbers.
27.	Exercise: Write a function that takes an array and reverses its elements.
28.	Exercise: Write a function that takes a 2D array and returns the trace of the matrix (sum of diagonal elements).
29.	Exercise: Write a function that takes two arrays and returns their dot product.
30.	Exercise: Write a function that takes a 1D array and returns a boolean array indicating whether each element is greater than 5.


## Objective: How do you import the NumPy library in Python?

In [3]:
import numpy as np

## Objective: What function in NumPy is used to create an array?

In [21]:
arr=np.array([])
arr

array([], dtype=float64)

## Objective: How do you create a 1D NumPy array containing the numbers 0 to 9?

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Objective: How do you create a 2D NumPy array with shape (3, 3) filled with zeros?

In [23]:
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Objective: How do you create an identity matrix of size 4x4?

In [25]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Objective: How do you get the shape of a NumPy array `arr`?

In [29]:
shape = arr.shape
shape

(4, 4)

## Objective: What function is used to get the total number of elements in a NumPy array `arr`?

In [33]:
np.size(arr)

16

## Objective: How do you get the data type of elements in a NumPy array `arr`?

In [37]:
data_type = arr.dtype
data_type

dtype('float64')

## Objective: How do you change the data type of elements in a NumPy array `arr` to float?

In [41]:
arr = arr.astype(int)
data_type = arr.dtype
data_type

dtype('int32')

## Objective: How do you create a 3x3 NumPy array with random values between 0 and 1?

In [43]:
arr = np.random.rand(3, 3)
arr

array([[0.48001261, 0.75313167, 0.02589705],
       [0.27209876, 0.98080844, 0.38915059],
       [0.00975845, 0.47980146, 0.44726495]])

## Objective: How do you flatten a 2D NumPy array `arr` into a 1D array?

In [49]:
flattened_arr=arr.flatten()
flattened_arr

array([0.48001261, 0.75313167, 0.02589705, 0.27209876, 0.98080844,
       0.38915059, 0.00975845, 0.47980146, 0.44726495])

## Objective: How do you reshape a 1D array `arr` of size 12 into a 3x4 array?

In [51]:
reshaped_arr = arr.reshape(3, 4)
reshaped_arr

ValueError: cannot reshape array of size 9 into shape (3,4)

In [58]:
#array in prev step was 3x3 therefore contained 9 elements
# creating an array with 12 elements to reshape into 3x4 
arr = np.arange(12)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
reshaped_arr = arr.reshape(3, 4)
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Open-ended: Write a code snippet to create a 5x5 matrix with values 1, 2, 3, ..., 25.

In [64]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Open-ended: Write a code snippet to create a 1D array of 20 linearly spaced values between 0 and 5.

In [66]:
arr = np.linspace(0, 5, 20)
arr

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Open-ended: Write a code snippet to create a 3x3 matrix where the diagonal elements are 1 and the off-diagonal elements are 0.

In [70]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Open-ended: Write a code snippet to create a 4x4 matrix filled with the value 7.

In [72]:
arr = np.full((4, 4), 7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## Open-ended: Write a code snippet to create an array containing the even numbers from 10 to 30.

In [74]:
arr = np.arange(10, 31, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

## Open-ended: Write a code snippet to create an array of 10 random integers between 50 and 100.

In [76]:
arr = np.random.randint(50, 101, size=10)
arr

array([96, 96, 80, 68, 97, 52, 55, 73, 56, 81])

## Exercise: Write a function that takes two arrays and returns their element-wise product.

In [82]:
def element_wise_product(array1, array2):
    # Ensure the arrays have the same length
    if len(array1) != len(array2):
        raise ValueError("Both arrays must have the same length")
    
    # Calculate the element-wise product
    product = [a * b for a, b in zip(array1, array2)]
    
    return product


In [86]:
array1 = [1, 2, 3]
array2 = [4, 5, 6]

result = element_wise_product(array1, array2)
print(result)


[4, 10, 18]


## Exercise: Write a function that takes an array and returns the maximum and minimum values.

In [88]:
def max_min(arr):
    return np.max(arr), np.min(arr)
max_min(arr)

(97, 52)

## Exercise: Write a function that normalizes an array (scales all values between 0 and 1).

In [90]:

def normalize(arr):
    return (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
normalize(arr)

array([0.97777778, 0.97777778, 0.62222222, 0.35555556, 1.        ,
       0.        , 0.06666667, 0.46666667, 0.08888889, 0.64444444])

## Exercise: Write a function that takes an array and returns the index of the maximum value.

In [96]:
def index_of_max(arr):
    return np.argmax(arr)

# Example usage
arr = [10, 20, 30, 25, 15]
result = index_of_max(arr)
print(result)  # Output: 2 (since 30 is the maximum value at index 2


2


## Exercise: Write a function that takes a 2D array and returns the sum of each row.

In [113]:
arr = np.arange(1, 26).reshape(5, 5)

In [115]:
def row_sums(arr):
    return np.sum(arr, axis=1)

row_sums(arr)

array([ 15,  40,  65,  90, 115])

## Exercise: Write a function that takes a 2D array and returns the sum of each column.

In [107]:
arr = np.arange(1, 26).reshape(5, 5)

In [117]:
def col_sums(arr):
    return np.sum(arr, axis=0)

col_sums(arr)

array([55, 60, 65, 70, 75])

## Exercise: Write a function that takes a 2D array and returns the transpose of the array.

In [125]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [127]:
def transpose(matrix):
    return np.transpose(matrix)
transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Exercise: Write a function that takes an array and removes all the even numbers.

In [141]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [143]:
def remove_even(arr):
    return arr[arr % 2 != 0]
remove_even(arr)

array([1, 3, 5, 7, 9])

In [145]:
remove_even(matrix)

array([1, 3, 5, 7, 9])

## Exercise: Write a function that takes an array and reverses its elements.

In [147]:
def reverse_array(arr):
    return arr[::-1]

reverse_array(arr)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Exercise: Write a function that takes a 2D array and returns the trace of the matrix (sum of diagonal elements).

In [151]:
def matrix_trace(arr):
    return np.trace(arr)
#The trace of a square matrix is the sum of its diagonal entries.
matrix_trace(matrix)

15

## Exercise: Write a function that takes two arrays and returns their dot product.

In [153]:
arr1=[1,2,3]
arr2=[4,5,6]

In [155]:
def dot_product(arr1, arr2):
    return np.dot(arr1, arr2)
dot_product(arr1, arr2)

32

In [163]:
a = [[1, 2], 
     [3, 4]]
b = [[4, 1], 
     [2, 2]]
dot_product(a,b)

array([[ 8,  5],
       [20, 11]])

## Exercise: Write a function that takes a 1D array and returns a boolean array indicating whether each element is greater than 5.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [165]:

def greater_than_five(arr):
    return arr > 5
greater_than_five(arr)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [167]:
arr = np.array([1, 2, 13, 4, 5, 0.6, 7, 0.8, 9, 10])
greater_than_five(arr)

array([False, False,  True, False, False, False,  True, False,  True,
        True])